language: objective-c
osx_image: xcode7.3
xcode_workspace: AeroGearOAuth2.xcworkspace
xcode_scheme: AeroGearOAuth2Tests
xcode_sdk: iphonesimulator 

before_install:
    - gem install cocoapods --pre -n /usr/local/bin

notifications:
  irc: "irc.freenode.org#aerogear"

branches:
  only:
    - master
